#bar := yuva\
foo := $(bar)\
bar := $(ugh)\
bar := Huh? \
all : \
	@echo "foo : "$(foo)\
	@echo "bar : " $(bar)


#foo = yuva\
foo += raju \
all :  \
	@echo "foo : " $(foo) 



#basu := /reetha/global    #cvcgdgcdcdv \
yuva := $(basu)/edge\
basu := raju\
all : \
	@echo "yuva : "$(yuva) 

#foo ?= reetha\
foo ?= global\
all : \
	@echo "foo : "$(foo)


foo := a.o b.o c.o
bar := $(foo:.o = .c)
all:
	@echo: "foo : "$(bar)

