/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class add */

#ifndef _Included_add
#define _Included_add
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     add
 * Method:    add_
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_add_add_1
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
