#include"headers.h"
void menu(void)
{
    printf("   \t1.user_strcpy\n"
            "\t2.user_strncpy\n"
            "\t3.user_strncat\n"
            "\t4.user_strncmp\n"
            "\t5.user_strrchr\n"
            "\t6.user_strspn\n"
            "\t7.user_strcasecmp\n"
            "\t8.user_strtok\n"
            "\t9.user_strcspn\n"
            "\t10.user_strstr\n"
            "\t11.squeeze\n"
            "\t12.isalnum\n"
            "\t13.isalpha\n"
            "\t14.isdigit\n"
            "\t15.isprint\n"
            "\t16.issxdigit\n"
            "\t17.isupper\n"
            "\t18.islower\n"
            "\t19.string rotation:\n"
            "\t20.mac_isalnum\n"
            "\t21.mac_isalpha\n"
            "\t22.mac_isdigit\n"
            "\t23.mac_isprint\n"
            "\t24.mac_isupper\n" 
            "\t25.mac_islower\n"
            "\t26.mac_isxdigit\n"	
            "\t27.comment remove\n"
            "\t28.fold a file\n"		
            "\t29.iscntrl\n"
            "\t30.syntax checker\n");
}

