/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNIC */

#ifndef _Included_HelloJNIC
#define _Included_HelloJNIC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNIC
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJNIC_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
